services:
  - type: web
    name: neural-horo-discord
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_bot.py
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: VK_USER_TOKEN
        sync: false
      - key: AUTO_POST_CHANNEL_ID
        sync: false